feat: add snaketopascal case tag
discordjs/discord-utils-bot pull request #107
Opened 2022-07-21 09:17 UTC by megatank58

2022-07-21 20:18 UTC, almeidx commented
Can you add `enum` related keywords?

2022-07-22 09:22 UTC, megatank58 commented
> Can you add `enum` related keywords?

Could you give an example?

2022-07-22 18:00 UTC, MrMythicalYT requested changes
for the Permissions, it is misspelled, and should probably be changed to be `PermissionFlagsBits`

2022-07-23 07:48 UTC, almostSouji requested changes
Should use a permission that actually exists and use PermissionFlagsBits export

2022-07-23 07:48 UTC, almostSouji commented on tags/tags.toml
> +• Permissions: `Permissions.FLAGS.GUILD_MESSAGES` -> `PermissionBitFields.Flags.GuildMessages`
```suggestion
• Permissions: `Permissions.FLAGS.SEND_MESSAGES` -> `PermissionFlagsBits.SendMessages`
```

2022-07-24 12:02 UTC, almostSouji approved these changes

2022-07-24 12:02 UTC, merged