chore(docs): rename discord.js specific commands
discordjs/discord-utils-bot pull request #120
Opened 2022-10-13 14:47 UTC by JPBM135

## Why?
Clarification, what dev means? Shouldn't v14 be stable?
- `discord-js` => `discord-js-v13`
- `discord-js-dev` => `discord-js-v14`

![image](https://user-images.githubusercontent.com/67063134/195629582-389f999c-40d7-418c-99d6-e782cfb08698.png)

2022-10-17 10:26 UTC, almostSouji requested changes

2022-10-18 11:02 UTC, JPBM135 commented on src/deployFunctions/deployGlobal.ts
> +	NpmReloadCommand,
Reverted in 843641d

2022-10-19 11:26 UTC, JPBM135 commented on src/functions/npm.ts
> +	customSources.clear();
Remove this, is unnecessary!
```suggestion
```

2022-10-19 11:26 UTC, JPBM135 commented on src/functions/npm.ts
> +			)}\`\`\`\nNew versions: \`\`\`json\n${JSON.stringify(newVersions, null, 4)}\`\`\``,
Improve this message formating

2022-10-19 11:26 UTC, JPBM135 commented on src/index.ts
>  logger.info(`Tag cache loaded with ${tagCache.size} entries.`);
```suggestion
void loadTags(tagCache);
logger.info(`Tag cache loaded with ${tagCache.size} entries.`);
await loadLatestNpmVersion(customSources);
logger.info({
    msg: 'Loaded latest npm versions for discord.js',
    ['v13-lts']: customSources.get('v13-lts'),
    latest: customSources.get('latest'),
})
```

2022-10-19 11:26 UTC, JPBM135 commented on src/functions/npm.ts
> +export async function loadLatestNpmVersion(customSources: Map<CustomSourcesString, string>): Promise<void> {
Add an Util function to check if the files are valid/exist

2023-02-25 13:35 UTC, almostSouji commented
needs a rebase

2023-02-26 08:23 UTC, JPBM135 commented
> needs a rebase

Okie

2023-03-08 22:48 UTC, jaw0r3k commented on src/interactions/docs.ts
> +			description: `${SUBCOMMAND_DESCRIPTION_PREFIX} discord.js@latest`,
you should so a rebase 
and add `hide` options

2023-03-11 12:36 UTC, jaw0r3k commented on src/interactions/docs.ts
> +				},
```suggestion
				},
				{
					type: ApplicationCommandOptionType.Boolean,
					name: 'hide',
					description: EPHEMERAL_DESCRIPTION,
					required: false,
				},
			],
```

2023-03-13 23:44 UTC, JPBM135 commented on src/interactions/docs.ts
> +				},
Will do!

2023-03-14 02:07 UTC, JPBM135 commented on src/interactions/docs.ts
> +				},
Done in e60978a

2023-04-02 18:40 UTC, almostSouji approved these changes

2023-04-02 18:41 UTC, merged