tag: generic-actionrow
discordjs/discord-utils-bot pull request #129
Opened 2022-11-06 20:05 UTC by MrMythicalYT

Add a tag for the generic in `ActionRowBuilder`

2022-11-06 20:08 UTC, jaw0r3k commented
new select menus? 🤔

2022-11-06 20:09 UTC, MrMythicalYT commented
> new select menus? 🤔

Those aren't even added to

2022-11-07 10:54 UTC, almostSouji requested changes

2022-11-07 10:54 UTC, almostSouji commented on tags/tags.toml
> +```js
```suggestion
```ts
```

minor nit, but when talking about types, should use typescript

2022-11-07 13:36 UTC, almostSouji commented on tags/tags.toml
> +When using `ActionRowBuilder` in TypeScript, you need to provide the generic, specifying what the action row holds
```suggestion
In TypeScript the `ActionRowBuilder` class has a generic type parameter that specifies the type of component the action row holds:
```

2022-11-07 14:10 UTC, merged