Add invite-tracker tag
discordjs/discord-utils-bot pull request #184
Opened 2023-10-12 19:04 UTC by Wolvinny

i added this tag since this is a very common question

2023-10-12 19:08 UTC, jaw0r3k commented
Can you format it?

2023-10-12 19:10 UTC, jaw0r3k commented on tags/tags.toml
> +keywords = ["track-invite", "used-invite", "invite-used"]
```suggestion
keywords = ["tracking-invites", "used-invite", "who-invited-a-user"]
```
prob better keywords

2023-10-12 19:12 UTC, jaw0r3k commented on tags/tags.toml
> +This feature is not yet documented for bots.
It wont be documented as far i know

2023-10-12 19:49 UTC, Wolvinny commented on tags/tags.toml
> +This feature is not yet documented for bots.
i saw an endpoint somewhere but no clue, could put the yet between () though

2023-10-12 20:31 UTC, Jiralite commented on tags/tags.toml
> +Discord does not provide the invite which a member used to join. To get the invite you would have to create an invite tracking system yourself.
"Discord does not provide the invite which a member used to join." = "This feature is not yet documented for bots.". The same words are written differently.

2023-10-12 21:36 UTC, Wolvinny commented on tags/tags.toml
> +Discord does not provide the invite which a member used to join. To get the invite you would have to create an invite tracking system yourself.
i have edited it now

2023-10-16 10:28 UTC, almostSouji requested changes

2023-10-16 10:28 UTC, almostSouji commented on tags/tags.toml
> +"""
- I feel like there is a lot of words not saying all that much
- I dont't think we need to address "manually check" in advice intended for bot developers (which are clearly trying to automate something here, often invite rewards or moderation features)
- added a bit of information to the unreliable part
- reworded to reflect that the "unsure if this will be available" is regarding the members tab (otherwise I already see people go "but we have the members tab now")

```suggestion

[invite-tracker]
keywords = ["tracking-invites", "used-invite", "who-invited-a-user"]
content = """ 
Discord does not provide the invite that a member used to join through the bot API.
- Tracking the uses of invites through the `inviteCreate` and `guildMemberAdd` events is unreliable and we recommend against it.
- Discord has not shared any plans to make the members tab available for bots
""" 
```

2023-10-17 22:23 UTC, Wolvinny commented on tags/tags.toml
> +"""
this indeed is better, i am not the best at properly wording stuff

2023-10-19 12:17 UTC, merged