Update v13-changes tag
discordjs/discord-utils-bot pull request #20
Opened 2021-08-05 15:56 UTC by anandre

Add another alias, fix the guide page link and edited the wording a bit.

2021-08-05 16:17 UTC, SpaceEEC approved these changes

2021-08-05 16:39 UTC, hellobafu commented
I already updated this in another PR, but I didn't add the alias.

2021-08-06 10:37 UTC, almostSouji commented
needs a rebase if you want to add the alias (merged #16 because it also took care of the removal of the in-progress part)

2021-08-06 10:37 UTC, almostSouji requested changes
needs a rebase if you want to add the alias (merged #16 because it also took care of the removal of the in-progress part)

2021-08-25 09:36 UTC, closed without merging