feat: add NodeJS version select + use @discordjs/builders + better types
discordjs/discord-utils-bot pull request #27
Opened 2021-08-07 00:15 UTC by Favna

- Use @discordjs/builders wherever applicable for markdown output.
- Add types for MDN
- Add types for Node
- Add "version" option to Node which uses options to select between 12, 14 and 16 (default)
- Changed the docs Algolia query to send API app/key with headers

This also means this PR supersedes / fixes #19. Sorry for stealing your PR @KrishAgarwal2811 but I had this planned for a while... lol

2021-08-07 00:44 UTC, iCrawl approved these changes

2021-08-07 23:20 UTC, NotSugden commented on src/functions/guide.ts
> +	}).then((res) => res.json() as Promise<AlgoliaSearchResult>);
```suggestion
	}).then((res) => res.json()) as AlgoliaSearchResult;
```

2021-08-07 23:20 UTC, NotSugden commented on src/functions/mdn.ts
> +			const result = await fetch(qString).then((r) => r.json() as Promise<MdnAPI>);
```suggestion
			const result = await fetch(qString).then((r) => r.json()) as MdnAPI;
```

2021-08-07 23:20 UTC, NotSugden commented on src/functions/node.ts
> +			const data = await fetch(url).then((r) => r.json() as Promise<NodeDocs>);
```suggestion
			const data = await fetch(url).then((r) => r.json()) as NodeDocs;
```

2021-08-09 20:42 UTC, almostSouji requested changes
needs a rebase

2021-08-11 09:07 UTC, almostSouji requested changes
option description nitpick, lgtm otherwise
will probably wait for said builders release before merging

2021-08-11 19:03 UTC, almostSouji approved these changes

2021-08-12 02:19 UTC, KrishAgarwal2811 commented
Wow that's a great change @Favna. I just had a temporary fix 😂.

2021-08-14 09:39 UTC, merged