feat(commands): add ddocs command
discordjs/discord-utils-bot pull request #34
Opened 2021-08-14 10:33 UTC by almostSouji

![image](https://user-images.githubusercontent.com/26532370/129443487-0eb0b2ce-a606-4492-a332-b1211e516ec4.png)

* introduce ddocs algolia command to search the discord developer documentation at https://discord.com/developers/docs/
* generalize algolia defaults
* rename guide env vars
* use builders formatting more consistently

2021-08-15 21:47 UTC, NotSugden commented on src/deployFunctions/deployGlobal.ts
> +						name: '2 results (default)',
isn't the default 3?
`const DEFAULT_ALGOLIA_RESULT_AMOUNT = 3;`

2021-08-21 19:27 UTC, iCrawl approved these changes

2021-08-22 00:43 UTC, almostSouji commented on src/deployFunctions/deployGlobal.ts
> +						name: '2 results (default)',
good point, but the constant is the thing that's wrong, fixing in next commit, meant to lower and see how that plays out and simply forgot about it quite some time ago

2021-08-23 15:40 UTC, vladfrangu requested changes

2021-08-23 15:40 UTC, vladfrangu commented on src/functions/discorddocs.ts
> +		} ${bold('discord developer docs results:')}\n${result.join('\n')}`,
```suggestion
		} ${bold('Discord Developer docs results:')}\n${result.join('\n')}`,
```

2021-08-23 15:51 UTC, vladfrangu approved these changes

2021-08-23 15:54 UTC, merged