chore: tags
discordjs/discord-utils-bot pull request #46
Opened 2021-09-11 15:42 UTC by hellobafu

* Add collection-array tag

2021-09-11 17:38 UTC, almostSouji requested changes

2021-09-11 17:38 UTC, almostSouji commented on tags/tags.toml
> +keywords = ["collection-array", "array", "array()", "collection array"]
```suggestion
keywords = ["collection-array", "collection array"]
```

Keep the keywords free of extra symbols, if possible (and `array` is too generic for what the tag conveys, this is not really about how arrays work, which that would suggest)

2021-09-11 19:01 UTC, almostSouji commented
Afterthought after the review: I think this can be made much more targeted, seeing that most people that want an array just have no idea how to iterate a Map structure, but have learned how arrays work. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#iterating_over_a_map and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach and https://discord.js.org/#/docs/collection/main/class/Collection?scrollTo=map are probably worth mentioning as well.

Unsure how to do that all compact enough to do in a tag yet, but I suppose with inline links on key words it should be possible, somehow.

2021-09-11 19:03 UTC, hellobafu commented
I thought about that as well, but I chose to exclude it because of the link nightmare. I'll include those as well.

2021-09-15 17:57 UTC, almostSouji requested changes

2021-09-15 17:57 UTC, almostSouji commented on tags/tags.toml
> +• If you you need the array, you can use [Map.values()](<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/values>), and do: `[...<Collection>.values()]` or `Array.
```suggestion
Converting a collection to an array:
• You can cover most use cases with the Collection structure itself:
• Iteration is possible with [`for...of`](<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#iterating_over_a_map>) over [`Collection#values`](<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/values>) or [`forEach`](<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/forEach>) and you can transform a Collection to an output array with [`Collection#map`](<https://discord.js.org/#/docs/collection/main/class/Collection?scrollTo=map>).
• You only need an array instead of a Collection if you are trying to find the index of an entry, in which case you can get one from [`[...collection.values()]`](<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/values>).
```

Thought about the phrasing a bit, and I feel like this is more concise and understandable, Array#from isn't really preferable over collecting the iterator with the spread operator, IMO. After suggestion would look something like this: 
![image](https://user-images.githubusercontent.com/26532370/133485047-3f627802-4b45-4259-8a1f-e087eb051c0b.png)

If you think there's still potential to improve on it, do feel free to apply a different approach, of course

2021-09-15 18:11 UTC, hellobafu commented on tags/tags.toml
> +• If you you need the array, you can use [Map.values()](<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/values>), and do: `[...<Collection>.values()]` or `Array.
Hmm. I see. I will think about it.

2021-09-16 16:30 UTC, almostSouji approved these changes

2021-09-17 09:46 UTC, iCrawl approved these changes

2021-09-17 09:49 UTC, merged