Fixed embed-files tag
discordjs/discord-utils-bot pull request #60
Opened 2021-12-22 09:45 UTC by KinectTheUnknown

Improved diff code-block to more precisely show the changes necessary to replace the old `MessageEmbed#attachFiles` method.

2021-12-22 10:48 UTC, kyranet requested changes

2021-12-22 10:48 UTC, kyranet commented on tags/tags.toml
> +-   .attachFiles([attachment]);
We could do it like this:
```suggestion
-   .attachFiles([attachment])
    .setTitle('Attachments')
    .setImage(`attachment://${attachment.name}`);
```

With the current code, the removal of the line would result on the removal of the semicolon, and without the rearrangement, the diff would be messier:

```diff
-   .setImage(`attachment://${attachment.name}`)
-   .attachFiles([attachment]);
+   .setImage(`attachment://${attachment.name}`);
```

2021-12-23 17:47 UTC, kyranet approved these changes

2021-12-24 01:00 UTC, almostSouji approved these changes

2021-12-24 01:01 UTC, merged