Tag: footer
discordjs/discord-utils-bot pull request #65
Opened 2022-01-12 14:31 UTC by thehairy

A smol tag for the footer deprecation warning.

2022-01-13 00:54 UTC, almostSouji approved these changes

2022-01-18 20:13 UTC, almostSouji approved these changes

2022-01-19 18:15 UTC, SpaceEEC approved these changes

2022-01-19 18:40 UTC, almostSouji requested changes

2022-01-19 18:40 UTC, almostSouji commented on tags/tags.toml
> +
remove empty line, there is enough spacing between text and code block as is

2022-01-19 18:41 UTC, almostSouji requested changes

2022-01-19 18:41 UTC, almostSouji commented on tags/tags.toml
> +[footer]
chosen main name should ideally reflect all changes

2022-01-19 18:47 UTC, almostSouji approved these changes

2022-01-19 18:50 UTC, merged