feat(*): rewrite commands to use autocomplete, restructure project to be easier to extend
discordjs/discord-utils-bot pull request #73
Opened 2022-03-29 17:50 UTC by almostSouji

- Use autocomplete for /guide
- Use autocomplete for /discorddocs (former /ddocs)
- Use subcommands for /docs to prevent arguments right of autocomplete, the ac depends on
- Use native crypto module to verify discord payloads, removing dependency on third party packages
- Automaticall prefix the description of test commands
- Move handling logic into separate file per application command type
- Fully remove ephemeral selection fallback
- Move to use yarn as package manager
- Escape some MD in MDN titles `*` `||` 

This builds on #52 as a larger scope rewrite
This PR is currently running, so tested in production

2022-03-29 18:49 UTC, SpaceEEC approved these changes

2022-03-29 20:38 UTC, kyranet approved these changes

2022-03-29 21:50 UTC, vladfrangu requested changes

2022-03-29 21:50 UTC, vladfrangu commented on src/functions/autocomplete/tagAutoComplete.ts
> +	if (query && query.length) {
Why don't you `query?.length`

2022-03-29 21:50 UTC, vladfrangu commented on src/handling/handleApplicationCommand.ts
> +					`Add the discord.js interaction to your server: [(click here)](<https://discord.com/api/oauth2/authorize?client_id=${process
Use the hyperlink util from /builders

2022-03-29 21:50 UTC, vladfrangu commented on src/index.ts
> +		const mdnResult = mdnData;
This is a useless var

2022-03-30 08:47 UTC, almostSouji commented on src/functions/autocomplete/tagAutoComplete.ts
> +	if (query && query.length) {
legacy from the selection ephemeral, can't even be nullish anymore

2022-03-30 08:50 UTC, almostSouji commented on src/index.ts
> +		const mdnResult = mdnData;
I think there used to be a typecast here, removed

2022-04-18 11:28 UTC, vladfrangu approved these changes

2022-04-18 15:08 UTC, merged