chore: tags
discordjs/discord-utils-bot pull request #76
Opened 2022-04-08 12:25 UTC by Syjalo

A new tag for interaction replies

2022-04-08 13:37 UTC, almostSouji requested changes
- Keywords too generic
- Spelling
- Link to guide as in other tags (link md syntax)

2022-04-08 13:37 UTC, almostSouji commented on tags/tags.toml
> +[interaction-acknowledged]
```suggestion
[already-acknowledged]
```
already-acknowledged is the essence of the error

2022-04-08 13:37 UTC, almostSouji commented on tags/tags.toml
> +keywords = ["interaction-acknowledged", "interaction", "acknowledged", "reply", "deferReply"]
```suggestion
keywords = ["already-acknowledged", "interaction-acknowledged"]
```
keywords need to be unique, some of these were way too generic

2022-04-08 13:37 UTC, almostSouji commented on tags/tags.toml
> +You have alredy replied to the interaction by `<Interaction>.reply()` or `<Interaction>.deferReply()`.
These are not the only possible initial responses (modals coming up as well), unsure if it's wise to list them all, but if you decide to do so, list all, I guess

2022-04-08 13:37 UTC, almostSouji commented on tags/tags.toml
> +• If you defered reply it's better to use `<Interaction>.editReply()`
deferred (spelling)
why is it "better"? implies that the current thing is also an option, which it really isn't

2022-04-10 16:57 UTC, Syjalo commented on tags/tags.toml
> +• If you defered reply it's better to use `<Interaction>.editReply()`
So it should be like this?
If you deferred reply use `<Interaction>.editReply()`

2022-04-17 09:11 UTC, iCrawl approved these changes

2022-04-18 08:29 UTC, almostSouji approved these changes

2022-04-18 08:30 UTC, merged