Tag: number-id
discordjs/discord-utils-bot pull request #80
Opened 2022-04-20 16:02 UTC by MrMythicalYT

A tag showing that Discord IDs must be represented as strings

2022-04-21 07:55 UTC, almostSouji requested changes
Good suggestion, but I think this should be added as a point and additional aliases to the "snowflake" tag instead.
(also supported by the keyword overlap in the CI run)

2022-04-21 20:29 UTC, monbrey commented on tags/tags.toml
> +• Discord IDs are too high to be represented as numbers in JavaScript, so they must be represented as strings
```suggestion
• Discord ids follow the snowflake format: [learn more](<https://discord.com/developers/docs/reference#snowflakes>)
• Discord ids are larger than Number.MAX_SAFE_INTEGER, the largest number that can represented in JavaScript, so they must be represented as strings
```

2022-04-21 20:31 UTC, almostSouji commented on tags/tags.toml
> +• Discord IDs are too high to be represented as numbers in JavaScript, so they must be represented as strings
maybe even turn it around so the "do this" comes before the "cannot do this", probably beneficial for selective reading (always name the thing you want people to do before you tell them what not to do)

2022-04-21 20:45 UTC, almostSouji requested changes
> 
> maybe even turn it around so the "do this" comes before the "cannot do this", probably beneficial for selective reading (always name the thing you want people to do before you tell them what not to do)

2022-04-22 19:30 UTC, almostSouji requested changes

2022-04-22 19:30 UTC, almostSouji commented on tags/tags.toml
> +• Discord ids must be represented as strings as they are larger than `Number.MAX_SAFE_INTEGER`, the largest number that can represented in JavaScript
```suggestion
• Discord ids must be represented as strings as they are larger than `Number.MAX_SAFE_INTEGER`, the largest number that can be represented in JavaScript
```

typo/missing word

2022-04-22 22:15 UTC, almostSouji approved these changes

2022-04-22 22:19 UTC, almostSouji approved these changes

2022-05-12 18:51 UTC, SpaceEEC approved these changes

2022-05-13 06:16 UTC, kyranet requested changes

2022-05-13 06:16 UTC, kyranet commented on tags/tags.toml
> +• Discord ids must be represented as strings as they are larger than `Number.MAX_SAFE_INTEGER`, the largest number that can be represented in JavaScript
The largest number is `Number.MAX_VALUE`, which is `1.7976931348623157e+308`. This is just the largest integer.
```suggestion
• Discord ids must be represented as strings as they are larger than `Number.MAX_SAFE_INTEGER`, the largest integer that can be represented in JavaScript
```

2022-05-13 15:25 UTC, merged