chore: tags
discordjs/discord-utils-bot pull request #81
Opened 2022-05-03 16:44 UTC by Syjalo

This PR updates `third-party-libraries` tag

2022-05-04 08:23 UTC, almostSouji requested changes
The current structure is a bit bulky. I think you can move the radio buttons one up to list buttons/modals and then link the information in the same lines. Also, prefer `discord.js@dev` so the version is directly fully visible

Also CI red - please run validation before committing.

2022-05-12 15:32 UTC, almostSouji commented on tags/tags.toml
> +• Modals (`discord.js@dev`): [learn more](<https://deploy-preview-1060--discordjs-guide.netlify.app/interactions/modals.html>)
```suggestion
• Buttons are supported natively: [learn more](<https://discordjs.guide/interactions/buttons.html>)
• Modals are available on the development branch (`discord.js@dev`): [learn more](<https://deploy-preview-1060--discordjs-guide.netlify.app/interactions/modals.html>) (stable release in version `13.7.0`)
```

2022-05-12 15:32 UTC, almostSouji approved these changes

2022-05-12 15:42 UTC, vladfrangu approved these changes

2022-05-12 15:51 UTC, iCrawl approved these changes

2022-05-12 18:51 UTC, SpaceEEC approved these changes

2022-05-13 06:16 UTC, kyranet approved these changes

2022-05-13 15:22 UTC, merged