add master-events tag
discordjs/discord-utils-bot pull request #9
Opened 2021-07-28 16:30 UTC by ToasterSticks

This PR adds the master-events tag

2021-07-28 16:59 UTC, Nekoyre commented
Can you add "master events" as a keyword? Other than that lgtm

2021-07-28 17:04 UTC, thehairy requested changes

2021-07-28 17:04 UTC, thehairy commented on tags/tags.toml
> +keywords = ["master-events", "me", "v13-events", "v13 events"]
```suggestion
keywords = ["master-events", "master events", "me", "v13-events", "v13 events"]
```

2021-07-28 21:14 UTC, iCrawl commented on tags/tags.toml
> +```
```suggestion
The `message` and `interaction` events have been renamed to `messageCreate` and `interactionCreate` respectively, to bring the library in line with Discord's naming conventions.

The old events still work, but you'll receive a deprecation warning until you switch over.

```diff
- client.on('message', message => { ... });
+ client.on('messageCreate', message => { ... });
- client.on('interaction', interaction => { ... });
+ client.on('interactionCreate', interaction => { ... });
```
```

2021-07-28 21:14 UTC, iCrawl commented on tags/tags.toml
> +keywords = ["master-events", "master events", "me", "v13-events", "v13 events"]
```suggestion
keywords = ["master-events", "master events", "v13-events", "v13 events"]
```

Def. remove the `me` one here, too ambigious

2021-07-28 21:17 UTC, anandre commented on tags/tags.toml
> +```
Wouldn't this fall under using the guide interaction to point users to the v13 changes guide?

2021-07-29 09:06 UTC, SpaceEEC approved these changes

2021-07-29 09:16 UTC, iCrawl approved these changes

2021-07-29 23:33 UTC, almostSouji commented
i'm not too sure i like the version specific tags, or the <somebranch> keywords in general
i feel like deprecated events and surrounding name and keywords would be much nicer

2021-07-30 11:20 UTC, thehairy requested changes
I agree with souji. Should named version-less.

2021-07-30 11:20 UTC, thehairy commented on tags/tags.toml
> +keywords = ["master-events", "master events", "v13-events", "v13 events"]
```suggestion
keywords = ["event-deprecation", "event deprecation", "messageCreate", "interactionCreate"]
```

2021-07-30 11:21 UTC, thehairy commented on tags/tags.toml
> +[master-events]
```suggestion
[event-deprecation]
```

2021-07-30 13:04 UTC, thehairy requested changes
Thats what we wanted to get rid of 🧹

2021-07-30 13:04 UTC, thehairy commented on tags/tags.toml
> +keywords = ["event-deprecation", "event deprecation", "master-events", "master events", "v13-events", "v13 events"]
```suggestion
keywords = ["event-deprecation", "event deprecation", "messageCreate", "interactionCreate"]
```

2021-07-30 13:06 UTC, thehairy approved these changes

2021-07-31 03:03 UTC, NotSugden commented on tags/tags.toml
> +"""
missing the closing backticks 🤣

2021-08-01 19:57 UTC, ToasterSticks commented
Since I butchered this one hard, I re-did it in #12 :mmLol:

2021-08-01 19:57 UTC, closed without merging